# Generated by Django 4.1.2 on 2022-10-25 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_condition', models.BooleanField()),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.songs')),
            ],
        ),
    ]
